### ISSUE TITLE
lantern's server seems offline for days.

### ISSUE THREAD

**Issue by EdwardAutumn** [getlantern/lantern-binaries#10]
@myleshorton
i have tried to ping the pro server,but only got the requirements time out.
oddly the free version works. 
i have been using lantern since 2015,i love the idea of lantern,but every time things like this happened,there is no response from the corporation at all,it sucks especially for the new users,they feeling like be thrown away or the company is cheating on them and those "gentle men" just become to rioters.can you hire a guy who speaks Chinese and can explain what's going on in situation like this?it would helps a lot,thank you.

**Comment by myleshorton** [comment]
Hi @EdwardAutumn thanks very much for your support and suggestions. We actually have recently hired someone who speaks Chinese who should be helpful answering more questions. Unfortunately the volume is such that it's unlikely we'll get to everyone, but we'll try.

We really focus the vast majority of our efforts on simply making Lantern work as well as it possibly can, and anything we do aside from that can be detrimental to that effort. We will try to improve in this area, and we should have Lantern back up and running for everyone soon (it works for most people now but clearly not everyone).

**Comment by myleshorton** [comment]
Did you submit your logs @EdwardAutumn?

**Comment by EdwardAutumn** [comment]
@myleshorton i used the report function on the client side.
if you don't mind ,could you tell me what happened to the last admin p3yrca(i believe that was his name?)
[logs.zip](https://github.com/getlantern/lantern-binaries/files/1425926/logs.zip)

**Comment by xpirad** [comment]
@myleshorton 
Hi,thanks for your continuous effort to improve lantern.
However,recent releases,including the latest one 4.4.0,doesn't seem to be working.
It says it's connected to japan server,but i can't even access google.com :(

I've been trying to send feedback through the "report an issue" button,but there's no reply at all.What is going on exactly?
