### ISSUE TITLE
Versioned binaries

### ISSUE THREAD

**Issue by MarcinWieczorek** [getlantern/lantern-binaries#13]
Hello. Thank you for developing lantern. Please store versioned releases somewhere so people can access older versions and have consistent checksums for a certain url. This is critical for packaging for ArchLinux.
Thanks

**Comment by joesis** [comment]
Hey, @MarcinWieczorek for some reason there are no versioned installers on GitHub, but they do exist on S3 bucket.

1. The latest release version and SHA are always available at below locations:
https://s3.amazonaws.com/lantern/lantern-installer-32-bit.deb
https://s3.amazonaws.com/lantern/lantern-installer-32-bit.deb.sha256
https://s3.amazonaws.com/lantern/lantern-installer-64-bit.deb
https://s3.amazonaws.com/lantern/lantern-installer-64-bit.deb.sha256

1. Versioned installers follow name convention, but no SHA files.
https://s3.amazonaws.com/lantern/lantern-installer-4.7.7-32-bit.deb
https://s3.amazonaws.com/lantern/lantern-installer-4.7.7-64-bit.deb

So in theory when a script detects a new release version, it can check if 4.7.8, 4.7.9, 4.8.0, 4.8.1, 5.0.0, 5.0.1, etc, exist, and compare the ETag to see if they are identical without actually download the file. Do you think it could help on automated packaging? We could add SHA files for each version, but I guess ETag comparasion should be good enough?

**Comment by joesis** [comment]
Actually, the commit message contains the version number, so it can be simply extracted instead of guessing. See https://github.com/getlantern/lantern-binaries/commit/b07f4999d7c379d92d7ee0249ef2723b32c6411f

**Comment by MarcinWieczorek** [comment]
It works fine, thanks! I used versioned debs. Think about releasing checksums and PGP signatures too.
I don't need to detect a release, just have a fixed link that always points to the same file and now I got it.

**Comment by joesis** [comment]
Perfect @MarcinWieczorek!
