### ISSUE TITLE
MAC上控制台打不开

### ISSUE THREAD

**Issue by 814154500** [getlantern/lantern-binaries#132]
Mac的10.14.5版，蓝灯的5.5.0版，打不开控制台
safari报错：
**无法与localhost建立安全连接**
chrome报错：
**此网站无法提供安全连接 
localhost 发送的响应无效。
ERR_SSL_PROTOCOL_ERROR**
firefox报错：
**An error occurred during a connection to localhost:57150. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG** 
curl报错：
**curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number**

**Comment by joesis** [comment]
@814154500 请访问http://localhost:57150/.... 而不是https.

**Comment by 814154500** [comment]
> @814154500 请访问http://localhost:57150/.... 而不是https.

访问http会自动跳到https啊
你确定这个是官方的认真的回答吗？

**Comment by joesis** [comment]
你看看是不是有什么浏览器设置或者插件强制跳转了https？蓝灯的本地管理界面是http的。

**Comment by 814154500** [comment]
> 你看看是不是有什么浏览器设置或者插件强制跳转了https？蓝灯的本地管理界面是http的。

谢谢你提供的本地管理界面是http的信息，确认了是safari自己的问题
按照[https://blog.csdn.net/thewindkee/article/details/80668974](url)的方式处理后已经解决
