### ISSUE TITLE
[bug] Failed to open Google & Gmail

### ISSUE THREAD

**Issue by TechQuery** [getlantern/lantern-binaries#2]
Dear @getlantern team, my professional account has something wrong:

## Google

When I search anything in Chrome's address bar directly, the URL generated like this:

https://www.google.com/search?q=lantern&rlz=1C1GCEA_enSG927SG927&oq=LANTERN&aqs=chrome.0.69i59j69i64j69i60l3.14960j0j7&sourceid=chrome&ie=UTF-8

First error thrown:

> ERR_TOO_MANY_REDIRECTS

Then the page will turn to blank, and the DevTools shows a new error:

> Failed to load resource: net::ERR_CONTENT_DECODING_FAILED

But, if I open https://www.google.com/ and type keywords in the home page, everything is OK...

## Gmail

I open https://gmail.com/, and the same error thrown:

> ERR_TOO_MANY_REDIRECTS

Then the page will turn to an Error page:

![image](https://user-images.githubusercontent.com/19969570/158128650-7b5ac6d2-0f51-49df-a81c-4611249bdb1e.png)

But in my Mobile Chome, Gmail works well with Lantern...

## Environment

- Lantern: latest version
- OS: Windows 10 21H1
- Network: China mainland

**Comment by ZondaHM** [comment]
I have the same issue when using Google search and Gmail

**Comment by TechQuery** [comment]
Resolved in latest version, thanks guys!
