### ISSUE TITLE
win10提示：状态无法将蓝灯设置为系统代理

### ISSUE THREAD

**Issue by myVictor** [getlantern/lantern-binaries#41]
提示无法设置系统代理，点击显示蓝灯也无法打开具体页面。

**Comment by myVictor** [comment]
![image](https://user-images.githubusercontent.com/7285684/50723020-f9d3c680-1112-11e9-99c5-7570cc143025.png) 点击显示也无法打开配置页面。

**Comment by CrisChr** [comment]
@myVictor 你好，我也遇到了这个问题，请问你解决了吗？

**Comment by myVictor** [comment]
重装系统解决了。
