### ISSUE TITLE
最近蓝灯好像不能用了？无法翻墙。怎么解决？已经用了最新的版本。专业版本

### ISSUE THREAD

**Issue by swelltt0576** [getlantern/lantern-binaries#47]

**Comment by azhiltz** [comment]
连接不上服务器，一直显示在connecting!!!

**Comment by coidx** [comment]
是的，我的也是一直显示连接中 @myleshorton 怎么解决？

**Comment by Ghostwithout** [comment]
你好，正在调查处理中，谢谢！

**Comment by FMIB-DSG** [comment]
@Ghostwithout 广州电信，2月份以来从来电脑版就没有连接上过，安卓版却可以用，电脑版和手机版线路不一样？不过我还是电脑用的多，请尽快解决吧。

**Comment by Gooloo-Lahm** [comment]
> 你好，正在调查处理中，谢谢！

所以调查处理的结果呢？好多天不能用了。

**Comment by azhiltz** [comment]
我这今天已经能够使用了，原因未知。。。。

**Comment by swelltt0576** [comment]
今天还是不能用啊。。。。

**Comment by Liaozhenting** [comment]
今天也不能用

**Comment by Ghostwithout** [comment]
你好，应该逐步恢复了，请重启Lantern试下，如果还是不行，请到应用内反馈问题，以便根据日志调查处理。谢谢！

**Comment by swelltt0576** [comment]
前几天，发现在ie下使用正常。

然后，确定是自己安装的chrome代理插件的问题。关闭插件，蓝灯使用正常。

**Comment by Gooloo-Lahm** [comment]
这都快半个月了吧？一直一直不能用，到底给我们一个说法呀！！！你们都这么对待用户的吗？

**Comment by rookie233333** [comment]
@swelltt0576 你使用的是什么代理插件造成的？

**Comment by gta0804** [comment]
为什么现在又无法使用了，能连接上但就是不能访问被屏蔽的网站，帮助上的各种方法都试过了，没有用啊

**Comment by xupeng2012** [comment]
大概从昨天中午开始就一直有问题了，显示连上了然后马上又正在连接中。。。

现在好像恢复正常了。。。

**Comment by EA2019** [comment]
6月2日依然上不了

**Comment by ONEMisaki** [comment]
免费的都比你们强，垃圾蓝灯。6月2日连上无网速，节点一直在跳

**Comment by ONEMisaki** [comment]
一时可以一时不可以，我还是买的专业版。对得起付费用户吗？

**Comment by Patrick-Yuying** [comment]
专业版
6月1号起PC端跟Android端同时扑街，今天暂时PC端可连接，Android依然故障

**Comment by yuanzongfan** [comment]
6月2 号开始 就不能用了 我的天啊 什么时候能弄好啊  安卓和window都不能用 佛了

**Comment by hechuweiran** [comment]
Mac版蓝灯老是意外退出，没有任何提示。

**Comment by jeffidamn** [comment]
我的也连不上，一直显示connecting！偶尔连上个一两分钟，然后继续断连或者闪退！

**Comment by javakl** [comment]
6.3 一会能用一会不能用，麻烦抓紧解决

**Comment by jeffidamn** [comment]
MAC版和安卓版都不能用了，什么时候能解决！

**Comment by amberxj** [comment]
我用的是windows的专业版，从6月一号开始就不行了，麻烦快点解决。

**Comment by BetterTogetherX** [comment]
我的也不能用，从6月2号开始

**Comment by Jakezheng66** [comment]
PRO版用户 温州电信 
上周都还正常 过个周末 回来上班 桌面版发疯了 极度不稳定 一直显示连接中  
连上了 一会又会掉了 自动重新连 这个过程一直在反复进行
再过一会儿 就干脆 自动关闭软件
麻烦赶紧解决  不然 工作不好开展

**Comment by amberxj** [comment]
我的是广东移动一直处于连接中...

**Comment by Jakezheng66** [comment]
6月3日开始
桌面版不能用
手机版可以使用

**Comment by qingliucs** [comment]
> Mac版蓝灯老是意外退出，没有任何提示。

windows版本的也是，从6月3日起，老是自动退出

**Comment by EnjoyWall** [comment]
6月3日，手机和电脑都无法稳定连接。几分钟就会断，就算连上了也只能维持一两分钟。

**Comment by fivexxxxx** [comment]
最新的 5.4.1 -20190603.043321 也不行哦，还是老样子

**Comment by sagemoni** [comment]
6.2开始发现，手机无法使用移动数据连接，6.3pc端经常断链

**Comment by qingliucs** [comment]
从晚上开始，我可以使用了哦

**Comment by qingliucs** [comment]
> 从晚上开始，我可以使用了哦

版本为Lantern 5.4.0

**Comment by guoguozaichangge** [comment]
mac 最新版一直显示正在连接中，有时候连接上，搜索东西就断开连接

**Comment by Licko0909** [comment]
我的上周开始出问题，一直连接中，连github都上不去。但是有时候又可以用，比如现在，莫名奇妙！

**Comment by Licko0909** [comment]
> 从晚上开始，我可以使用了哦

我的也是，今天可以用了

**Comment by shalalalatuzki** [comment]
坐标广州，win系统，从五月底开始就不能用了

**Comment by Jakezheng66** [comment]
今天恢复正常使用 版本5.4.1

**Comment by xupeng2012** [comment]
从下午四点开始又出现同样的问题了…这是软件的问题还是遭到恶意攻击了？

**Comment by Licko0909** [comment]
又用不了了！！！！

**Comment by amberxj** [comment]
从1号开始一直用不了，一直连接中，节点一直跳，到底是什么问题？？

**Comment by fivexxxxx** [comment]
今天凌晨开始好像可以用，，倒今天中午12点后，持续倒现在一直罢工中...

**Comment by ryouxin** [comment]
官方大大出来给个回应啊 一直使用不了啊

**Comment by annamommy** [comment]
我从6.4号开始win7 电脑端没问题，但是安卓端依然无法连接，节点一直变，但是始终没连上。

**Comment by Jakezheng66** [comment]
桌面版稳定了一天半
现在又开始发疯了 一直在重连
手机端目前正常

**Comment by dengbp** [comment]
从上周6开始就用不了了。一直连不上，还会自动退出

**Comment by cadenwang1234** [comment]
x的买来之后从来没能正常用过，反馈问题，客服从来没回复过我，忙着给自己爹们发丧呢？行，这两年的钱就当给你们爹烧纸了

**Comment by fishingcat2012** [comment]
请赶快解决，目前手机端5.4/5.4.1版本都不能上，广州移动

**Comment by canyuelantian** [comment]
我的4天了，两台电脑，一台能连接，一台无法连接，求解决方案，卸载几遍了

**Comment by fym3576** [comment]
6月6号 5.4.1仍不能用.

**Comment by WUT-xiaoming** [comment]
真的垃圾，压根儿没人管

**Comment by WUT-xiaoming** [comment]
第一次买，也是最后一次了

**Comment by WUT-xiaoming** [comment]
客服人员都死了吗？能出来说句话吗

**Comment by Licko0909** [comment]
> 我的4天了，两台电脑，一台能连接，一台无法连接，求解决方案，卸载几遍了

我一台都链接不了@canyuelantian

**Comment by qitianzjf** [comment]
win7的连的上，但是win10和安卓的一直在连接中，服务器位置还在一直跳

**Comment by qq361933172** [comment]
用不了,已经两周了,用不了!!!!!

**Comment by jeffidamn** [comment]
本来已经好一点了，一直连着，退出一下结果再也连不上了！！

**Comment by AndyXieSH** [comment]
连接不了

**Comment by 939248060** [comment]
最近出啥问题了，官方都不出来说一下是什么情况吗，

**Comment by GarfieldLover** [comment]
刚买了2年的，一直不能用，退款没人理

**Comment by celesius** [comment]
连接不上啊老板们，尽快解决啊

**Comment by Nepoli** [comment]
连不上 你们都用什么版本

**Comment by dlxxlzd** [comment]
手机电脑都不能连接

**Comment by kainchow** [comment]
> 我的也连不上，一直显示connecting！偶尔连上个一两分钟，然后继续断连或者闪退！

从来就没连上过，Ubuntu18.04

**Comment by kainchow** [comment]
> 手机电脑都不能连接

同手机电脑都不能连接

**Comment by kainchow** [comment]
一直连不上，请问各位大神还有其他翻墙软件推荐的吗？Ubuntu18.04

**Comment by BetterTogetherX** [comment]
都快十天了，还是连接不上。

**Comment by Jakezheng66** [comment]
6月1日到4日无法使用
5号开始手机和电脑可以正常使用
偶尔会断 
大家可以建个群 相互交流一下

**Comment by ccccccode** [comment]
@Ghostwithout 这么久了，还没解决好吗

**Comment by jeffidamn** [comment]
安卓版完全不能用，究竟什么时候能好啊

**Comment by Jakezheng66** [comment]
刚刚电脑版发疯了 和客户WhatsApp刚聊了一半 就一直断 一直连 郁闷
看了几个群 这情况不止蓝灯有 很多VPN都出问题了
我在想不会是香港那边的活动 造成的吧

**Comment by BetterTogetherX** [comment]
还是连接不上呀.你们的可以连接不？

**Comment by javakl** [comment]
还是不能用，时好时坏，无法进行使用






在 2019-06-13 11:35:30，"BetterTogetherX" <notifications@github.com> 写道：


还是连接不上呀.你们的可以连接不？

**Comment by hewentaowx** [comment]
同连接不上 ，一点都不稳定  还剩6个月专业版 准备换一个了

**Comment by eidson0408** [comment]
怎么回事，还有5个月，退款吧！！！

**Comment by ChnZhgH** [comment]
目前wiin10一直连不上，希望快点解决

**Comment by xupeng2012** [comment]
现在这个版本 （5.4.6）从昨天起到现在比较稳定了。。。

**Comment by ericssonruffy** [comment]
visiting recovered since yesterday, MacOS.

**Comment by melonfish** [comment]
> 6月6号5.4.1仍不能用。
6月份开始5.4.1一直用不了，MacOs版本，坐标广州

**Comment by eidson0408** [comment]
Lantern 5.4.6 (20190612.162330)   20190618还是无法连接！！！！！！

**Comment by Xizor-Bayes** [comment]
5.4.6版本可以用了

**Comment by Licko0909** [comment]
5.4.0也可以用

**Comment by javakl** [comment]
mac 上怎么能找到这个版本的蓝灯呢






在 2019-06-20 15:52:43，"Licko0909" <notifications@github.com> 写道：


5.4.0也可以用

**Comment by javakl** [comment]
mac 上怎么能找到这个版本的蓝灯呢





在 2019-06-20 15:51:04，"Xizor-Bayes" <notifications@github.com> 写道：


5.4.6版本可以用了

**Comment by caibiao** [comment]
六月份就没怎么能连上成功

**Comment by eidson0408** [comment]
git上下载最新的
________________________________
发件人: caibiao <notifications@github.com>
发送时间: 2019年6月21日 10:29
收件人: getlantern/lantern-binaries
抄送: eidson0408; Comment
主题: Re: [getlantern/lantern-binaries] 最近蓝灯好像不能用了？无法翻墙。怎么解决？已经用了最新的版本。专业版本 (#47)


六月份就没怎么能连上成功

―

**Comment by MRXia** [comment]
手机上新版的可以用了吗？

**Comment by eidson0408** [comment]
没用过手机上的，IOS版估计流产了



------------------ 原始邮件 ------------------
发件人: "夏子健"<notifications@github.com>; 
发送时间: 2019年6月21日(星期五) 晚上7:25
收件人: "getlantern/lantern-binaries"<lantern-binaries@noreply.github.com>; 
抄送: "Zhueidson"<eidson@outlook.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [getlantern/lantern-binaries] 最近蓝灯好像不能用了？无法翻墙。怎么解决？已经用了最新的版本。专业版本 (#47)




手机上新版的可以用了吗？

**Comment by fivexxxxx** [comment]
LANTERN 5.4.6. win10 还是不能用啊，你们都能用了吗？？？

**Comment by eidson0408** [comment]
可以用了，只不过有时候会掉线，不太稳定



------------------ 原始邮件 ------------------
发件人: "fivexxxxx"<notifications@github.com>; 
发送时间: 2019年6月22日(星期六) 晚上9:50
收件人: "getlantern/lantern-binaries"<lantern-binaries@noreply.github.com>; 
抄送: "Zhueidson"<eidson@outlook.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [getlantern/lantern-binaries] 最近蓝灯好像不能用了？无法翻墙。怎么解决？已经用了最新的版本。专业版本 (#47)




LANTERN 5.4.6. win10 还是不能用啊，你们都能用了吗？？？

**Comment by qzsSock** [comment]
我擦 刚刚买半天能退款不,我真是服了

**Comment by HackerDaKun007** [comment]
> 怎么回事，还有5个月，退款吧！

请问要怎么退款！！

**Comment by eidson0408** [comment]
不知道啊，我也还有5个月


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Da kun <notifications@github.com>
发送时间: 2019年6月26日 15:50
收件人: getlantern/lantern-binaries <lantern-binaries@noreply.github.com>
抄送: eidson0408 <eidson@outlook.com>, Comment <comment@noreply.github.com>
主题: 回复：[getlantern/lantern-binaries] 最近蓝灯好像不能用了？无法翻墙。怎么解决？已经用了最新的版本。专业版本 (#47)




怎么回事，还有5个月，退款吧！

请问要怎么退款！！

**Comment by HackerDaKun007** [comment]
我还有11个月多，要死了！我刚才升级了版本为5.4.7好像稳定了。

在 2019年6月26日，下午4:23，eidson0408 <notifications@github.com<mailto:notifications@github.com>> 写道：

不知道啊，我也还有5个月


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Da kun <notifications@github.com<mailto:notifications@github.com>>
发送时间: 2019年6月26日 15:50
收件人: getlantern/lantern-binaries <lantern-binaries@noreply.github.com<mailto:lantern-binaries@noreply.github.com>>
抄送: eidson0408 <eidson@outlook.com<mailto:eidson@outlook.com>>, Comment <comment@noreply.github.com<mailto:comment@noreply.github.com>>
主题: 回复：[getlantern/lantern-binaries] 最近蓝灯好像不能用了？无法翻墙。怎么解决？已经用了最新的版本。专业版本 (#47)




怎么回事，还有5个月，退款吧！

请问要怎么退款！！

**Comment by hanguanmiao** [comment]
发现最新版本，代理所有流量可以用

**Comment by zouminhua** [comment]
要么就干脆链接不上，要么显示链接上了却浏览不了网页看不了视频，偶尔能链接上了但是很快又断了，这种情况都已经持续3个多月了，作为付费用户很受伤，请问能退款吗

**Comment by HackerDaKun007** [comment]
退不了！我们都是没想到蓝灯这么无节操，毫无底线(无赖)的故意不给用户退款的…,我算是见识到了！！！！

在 2019年7月29日，下午10:01，zouminhua <notifications@github.com<mailto:notifications@github.com>> 写道：


要么就干脆链接不上，要么显示链接上了却浏览不了网页看不了视频，偶尔能链接上了但是很快又断了，这种情况都已经持续3个多月了，作为付费用户很受伤，请问能退款吗
