### ISSUE TITLE
蓝灯专业版无法使用 清理数据后试用版正常

### ISSUE THREAD

**Issue by ShirasawaSama** [getlantern/lantern-binaries#72]
安卓 最新版
**已经两天不能连接了**
先前登陆后清理数据后退回试用版可连接一会（不到三分钟），等自动登录之后就掉线了，任何网站无法连接。
并且手动点击退出登录显示当前无法退出。

现在此方法也失效。
重装后点击升级显示缺少`Pro Token`，并且不会出现授权码也不能够使用邮箱号登录。

**Comment by differentlight** [comment]
同样问题，专业版今天开始电脑，手机都无法使用。自动分配使用HK代理。

**Comment by AisakaTaika** [comment]
同样的问题，而且连上没多久就会断。

**Comment by nordefornet** [comment]
同样的问题 也是2天了 删掉重新安装不到一分钟又断开连不上了

**Comment by hiquanta** [comment]
一样

**Comment by Ghostwithout** [comment]
@ShirasawaSama 请到https://github.com/getlantern/download 下载最新版。授权设备登陆，可参照如下两种方法：
－在新设备lantern界面左边菜单点击“授权设备使用专业版”，在里面输入购买时的邮箱，验证码就会发到你的邮箱（如果没收到看下垃圾邮件），然后输入验证码即可； 
－在新设备选择“授权设备使用专业版”，该界面会收到验证码，然后请到专业版设备输入验证码。谢谢！

**Comment by Ghostwithout** [comment]
其他反馈不能使用的用户请到应用内反馈，以便根据日志调查。谢谢！ @differentlight @AisakaTaika @nordefornet @hiquanta

**Comment by CMinHong** [comment]
> @ShirasawaSama 请到 [https://github.com/getlantern/download ](https://github.com/getlantern/download%C2%A0)
> 下载最新版。授权设备登陆，可参照如下两种方法：
> －在新设备lantern界面左边菜单点击“授权设备使用专业版”，在里面输入购买时的邮箱，验证码就会发到你的邮箱（如果没收到看下垃圾邮件），然后输入验证码即可；
> －在新设备选择“授权设备使用专业版”，该界面会收到验证码，然后请到专业版设备输入验证码。谢谢！

404

**Comment by ShirasawaSama** [comment]
> @ShirasawaSama 请到 [https://github.com/getlantern/download ](https://github.com/getlantern/download%C2%A0)
> 下载最新版。授权设备登陆，可参照如下两种方法：
> －在新设备lantern界面左边菜单点击“授权设备使用专业版”，在里面输入购买时的邮箱，验证码就会发到你的邮箱（如果没收到看下垃圾邮件），然后输入验证码即可；
> －在新设备选择“授权设备使用专业版”，该界面会收到验证码，然后请到专业版设备输入验证码。谢谢！

已尝试 依旧无效 不能连接 已经差不多一周了 仅安卓设备异常 其它平台均正常使用

**Comment by ShirasawaSama** [comment]
目前已正常 但速度还是非常缓慢
