### ISSUE TITLE
lantern 5.4.0 pro 6 月 1 号开始无法链接

### ISSUE THREAD

**Issue by quzhixue-Kimi** [getlantern/lantern-binaries#84]
我有专业版账号 
6月 1 号开始无法链接,即使链接后也无法访问部分网站,系统macbook pro,OS 是 10.14.5 最新的
无其他 工具.

请问是北京地区被封了吗?

**Comment by innocentbrain** [comment]
坐标深圳，无法连接，or 连接后依然无法访问

**Comment by ccccccode** [comment]
我的也无法连接，已经弄了一天了，不管是电脑还是手机都用不了，坐标长沙

**Comment by 4vil4ric** [comment]
最近敏感期，我今天也用了，也不行。坐标重庆

**Comment by jeal1919** [comment]
长沙电信 6月1日 开始 PC端无法使用，手机端可以使用

**Comment by yaoice** [comment]
能退款吗？

**Comment by JellyWang7** [comment]
退钱吧，真的是付了钱还这么不稳定

**Comment by jawhiow** [comment]
同不能用，坐标上海！6.1号开始~

**Comment by AmenLin** [comment]
坐标深圳 6月2号开始无法连接 过了最近敏感时期会不会恢复正常阿
