### ISSUE TITLE
6月份 蓝灯突然不能用了 

### ISSUE THREAD

**Issue by desstiony** [getlantern/lantern-binaries#85]
如题 蓝灯显示连接成功 但是不能用 卸载了下载最新版还是不行 问了几个用蓝灯的朋友都不能用了 怎么办？

**Comment by boxshadow** [comment]
突然不能用 +1

**Comment by fivexxxxx** [comment]
pm 12:xx, yesterday， lantern strike continues until now！！！
It has been unable to connect to restricted sites. For example: youtbue... Pls resolve it as soon as possible.Remember earlier，A similar situation has occurred about two weeks！！

**Comment by desstiony** [comment]
可能6月份了 审查比较 严格 只能等修复了 问题是连个可以联系的人都没有 到期了准备换了

**Comment by Tjlastnumber** [comment]
这段时间严, 大部分翻墙都不能用了

**Comment by mk-wang** [comment]
低调度过六月初 不然以后都没的用

**Comment by boxshadow** [comment]
> 低调度过六月初 不然以后都没的用

这波操作这么骚吗

**Comment by Patrick-Yuying** [comment]
github可以直接访问的吗

**Comment by desstiony** [comment]
老哥们 把蓝灯的语言改为英文就可以了 亲测可用

**Comment by boxshadow** [comment]
> 老哥们 把蓝灯的语言改为英文就可以了 亲测可用

666

**Comment by ccccccode** [comment]
切换英文可以用，可能有的时候等待连接的时间有点长，但起码还是能用的，不过断的也很快

**Comment by boxshadow** [comment]
> 切换英文可以用，可能有的时候等待连接的时间有点长，但起码还是能用的，不过断的也很快

不知道什么时候就自动退出😳

**Comment by desstiony** [comment]
低调度过这段时间

**Comment by wstee** [comment]
用不了，哈哈  沦陷了

**Comment by MarsAllianceZ** [comment]
时断时续，我这已经两天了，何时能修复这个问题？

**Comment by medz** [comment]
> 突然不能用 +1
> 表面上是已经连接上的状态, 只要一访问被墙掉的资源,马上就断开了, 并且整个设备都没有网络了
> Android+Mac Os 10.14.5

我擦嘞～原来是你～

**Comment by boxshadow** [comment]
> > 突然不能用 +1
> > 表面上是已经连接上的状态, 只要一访问被墙掉的资源,马上就断开了, 并且整个设备都没有网络了
> > Android+Mac Os 10.14.5
> 
> 我擦嘞～原来是你～

哪哪儿都有你 🐶

**Comment by tyxxzjpdez** [comment]
> > 切换英文可以用，可能有的时候等待连接的时间有点长，但起码还是能用的，不过断的也很快
> 
> 不知道什么时候就自动退出flushed

升级到5.4.1，不再自动退出

**Comment by ccccccode** [comment]
> > > 切换英文可以用，可能有的时候等待连接的时间有点长，但起码还是能用的，不过断的也很快
> > 
> > 
> > 不知道什么时候就自动退出flushed
> 
> 升级到5.4.1，不再自动退出

老哥，请问下5.4.1在哪下载，我现在的还是5.4.0，检查更新也还是5.4.0

**Comment by tyxxzjpdez** [comment]
> > > > 切换英文可以用，可能有的时候等待连接的时间有点长，但起码还是能用的，不过断的也很快
> > > 
> > > 
> > > 不知道什么时候就自动退出flushed
> > 
> > 
> > 升级到5.4.1，不再自动退出
> 
> 老哥，请问下5.4.1在哪下载，我现在的还是5.4.0，检查更新也还是5.4.0

首先，升级以后似乎不一定依旧稳定，不过我的还行，其他人仍会有问题，详见https://github.com/getlantern/lantern-binaries/issues/88
然后，5.4.1版本的话一般直接下载最新版就好，记得是在https://github.com/getlantern/download/wiki下载。如果还是找不到最新版，那么在https://github.com/getlantern/lantern-binaries找到介绍为5.4.1的，下载相应平台就可以了

**Comment by gmail12** [comment]
这个产业链最终的收益人是谁？-------- Original Message --------Subject: Re: [getlantern/lantern-binaries] 6月份 蓝灯突然不能用了  (#85)From: boxshadow To: getlantern/lantern-binaries CC: Subscribed 



突然不能用 +1

表面上是已经连接上的状态, 只要一访问被墙掉的资源,马上就断开了, 并且整个设备都没有网络了

Android+Mac Os 10.14.5



我擦嘞～原来是你～



哪哪儿都有你 🐶

**Comment by hubing130** [comment]
> 如题 蓝灯显示连接成功 但是不能用 卸载了下载最新版还是不行 问了几个用蓝灯的朋友都不能用了 怎么办

低调度过这段时间

**Comment by snlo** [comment]
> 老哥们 把蓝灯的语言改为英文就可以了 亲测可用

亲测可用，另外我增加了我的DNS服务器

**Comment by ZhangTeng4070** [comment]
第一次用蓝灯，买了两年的，结果刚用一个月就遇到这种特殊时期了，郁闷。。什么时候好啊，这都8号了

**Comment by hubing130** [comment]
我是快到期了、在考试要不要续

在 2019年6月8日星期六，张腾 <notifications@github.com> 写道：

**Comment by janehans** [comment]
沦陷了，今天仍在沦陷中

**Comment by magasea** [comment]
沦陷中

**Comment by huyunyadi** [comment]
蓝灯也难逃这命运，看来不是拦不住，只是看拦不拦而已

**Comment by ZhangTeng4070** [comment]
现在免费版能用了，但付费版还是连不上

**Comment by frankzhong** [comment]
人才啊，意大利炮呢

**Comment by frankzhong** [comment]
人才啊，把我的意大利炮拉出来

**Comment by hubing130** [comment]
怎么做到的

在 2019年6月4日星期二，snlo <notifications@github.com> 写道：

**Comment by jebai0521** [comment]
> 低调度过这段时间

问题没有解决啊，怎么Close了

**Comment by ZziL** [comment]
切换英文版？如何切换？

**Comment by ZziL** [comment]
切换英文版真的有用吗？期待  还有的是谁能科普一下为什么最近是特殊时期啊？查的这么严？还有就是要持续多久的

**Comment by lixiaoxi905** [comment]
废了 就没有相关人员跳出来说一下的嘛～挂了那么久

**Comment by snlo** [comment]
临近重大敏感事件，全面封杀VPN，这段时间还是省省吧

**Comment by weihan0917** [comment]
真的很讨厌不行也不弹个画面说明一下，都不知道怎么办好

**Comment by BobZhangCHN** [comment]
进入github里，下载最新的5.4.6，然后使用免费版。亲测可用

**Comment by DianeSzretlek** [comment]
下载了5.4.6，但时断时续，不过比之前的好了，起码能登上几分钟

**Comment by qq282918963** [comment]
> 进入github里，下载最新的5.4.6，然后使用免费版。亲测可用

不能用啦~~~

**Comment by hjy1560** [comment]
就香港的还能用，不过蓝灯不能让用户手动切这是一个大毛病--我一直跑韩国，后来什么都打不开，好坑，有大半月了

**Comment by ouyangzhigang** [comment]
mac版本lantern已经很不稳定，网络经常断开，有姐姐办法吗？

**Comment by weihan0917** [comment]
为什么到现在蓝灯还是不稳定，特别安桌版

**Comment by skccw** [comment]
北京电信不能用，北京联通可以用。

**Comment by wenwenbaba** [comment]
大佬，会员费都收了。咱也不说退不退的了。 你多整几台服务器么。 要不然快窒息了。。。

**Comment by Johnstfrank** [comment]
极不稳定啊现在

**Comment by JeremyShi628** [comment]
已经有大概两个月无法使用了。显示连接上了，只要一尝试连接被墙网站就断开连接。三次邮件support@getlantern.org，没有收到任何回复。今日再次尝试，成功连接几分钟后又再次断开。有没有哪里可以联系到官方呢？不能用至少给个说法呗，专业版还有16个月，这钱算是扔水里了。

**Comment by ZziL** [comment]
官方已跑路 有事烧纸

JeremyShi628 <notifications@github.com> 于2019年7月17日周三 下午4:46写道：

**Comment by DianeSzretlek** [comment]
亲测Linux依然可以用，但我另一台的windows就不行了，所以到底是为什么？？？？




| |
陈赛楠
邮箱：15195907703@163.com
|

签名由 网易邮箱大师 定制

在2019年07月19日 10:13，啊良梓是我 写道：
官方已跑路 有事烧纸

JeremyShi628 <notifications@github.com> 于2019年7月17日周三 下午4:46写道：

**Comment by mzw-g** [comment]
刚续完专业版还有24个月呢，连续2个月不稳定。是不是凉凉了啊。
