### ISSUE TITLE
@蓝灯

### ISSUE THREAD

**Issue by ZYQChina** [getlantern/lantern-binaries#91]
昨天我已经给你们反馈了,为什么没有回复呢??说了一直在连接中无法访问网络,如果正在解决或者已经解决请给我们一个回复,OK?
#89 是我昨天提交的,今天还是不能用,也没有收到你们的回复

**Comment by alicksnake22** [comment]
不是那么稳定，可惜刚续费了

**Comment by SunnyJoo** [comment]
> 不是那么稳定，可惜刚续费了

有时间,自己搭建一个吧

**Comment by SunnyJoo** [comment]
@myleshorton @oxtoacart @atavism

**Comment by Teragump** [comment]
散步呢，难度陡增~

**Comment by SunnyJoo** [comment]
@oxtoacart @myleshorton

**Comment by wstee** [comment]
今天又永不了，哈哈

**Comment by Ghostwithout** [comment]
我们正在全力修复，请使用遇到困难的用户到应用内反馈问题，谢谢！

**Comment by SunnyJoo** [comment]
@Ghostwithout 你们反馈之后也收不到回复呀,只能在这里@你们了

**Comment by JellyWang7** [comment]
> 我们正在全力修复，请使用遇到困难的用户到应用内反馈问题，谢谢！

反馈了但是问题也没有完全解决呀

**Comment by HHHuaX** [comment]
> 
> 
> 我们正在全力修复，请使用遇到困难的用户到应用内反馈问题，谢谢！

加油啊，应用内已经反馈了好几天了。。我才刚续的一年专业版。。。这种稳定性还不如一些小众产品。。

**Comment by Patrick-Yuying** [comment]
> @Ghostwithout 给你们反馈之后也收不到回复呀,只能在这里@你们了

枪打出头鸟倒是合乎常理...不过“快速稳定安全地访问自由的互联网”也是任重道远呐...

**Comment by SunnyJoo** [comment]
> > @Ghostwithout 给你们反馈之后也收不到回复呀,只能在这里@你们了
> 
> 枪打出头鸟倒是合乎常理...不过“快速稳定安全地访问自由的互联网”也是任重道远呐...

我不知道你为什么这么说,我认为我作为一个消费者有权这样做,如今这么繁华的世界还有你这样的人,算是正常吧,什么时候都有那么一批这样心里的人

**Comment by Teragump** [comment]
> > > @Ghostwithout 给你们反馈之后也收不到回复呀,只能在这里@你们了
> > 
> > 
> > 枪打出头鸟倒是合乎常理...不过“快速稳定安全地访问自由的互联网”也是任重道远呐...
> 
> 我不知道你为什么这么说,我认为我作为一个消费者有权这样做,如今这么繁华这么美的世界还有你这样的人,算是正常吧,什么时候都有一批这样心理的人

虽然是合理消费需求，但毕竟是灰色领域，那个老哥的意思也只是调侃官方吧。。。

**Comment by SunnyJoo** [comment]
> > > > @Ghostwithout 给你们反馈之后也收不到回复呀,只能在这里@你们了
> > > 
> > > 
> > > 枪打出头鸟倒是合乎常理...不过“快速稳定安全地访问自由的互联网”也是任重道远呐...
> > 
> > 
> > 我不知道你为什么这么说,我认为我作为一个消费者有权这样做,如今这么繁华这么美的世界还有你这样的人,算是正常吧,什么时候都有一批这样心理的人
> 
> 虽然是合理消费需求，但毕竟是灰色领域，那个老哥的意思也只是调侃官方吧。。。

官方也不会怎么做的,有问题解决问题而已,有bug都不提,那谁知道?

**Comment by Licko0909** [comment]
我刚刚续费了两年，就用不了了

**Comment by LamHeikit** [comment]
> 我刚刚续费了两年，就用不了了

哎 我也还有两年 这都一个星期过去了 粽子都吃上了 希望能赶在我吃月饼的时候修好

**Comment by WUT-xiaoming** [comment]
真的太垃圾了吧

**Comment by Teragump** [comment]
昨晚开始我的又可以用了。。。

**Comment by SunnyJoo** [comment]
> 昨晚开始我的又可以用了。。。

时好时坏的,大部分时间是连接上之后用不到十分钟就掉,然后就连接不上了

**Comment by SimpleQgw** [comment]
https://www.yahaha.win/auth/register?code=DMPJ1ILlePhz
用这个试试 网速快也很稳定

**Comment by Noname3031** [comment]
上网工具变成断网神器 噗
